org.gradle.jvmargs=-Xmx6144M -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.compiler.execution.strategy=daemon
kotlin.incremental=true
android.useAndroidX=true
android.enableJetifier=false
org.gradle.unsafe.configuration-cache=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.injected.testOnly=false
android.enableR8.fullMode=true
